### ISSUE TITLE
this does not work on latest angular2

### ISSUE THREAD

**Issue by gauravbhanderi231** [aikeru/Angular2Kendo#1]
Hi,

i tried using the sample with latest Angular2 version. I get a couple of errors. 
1. bindings: [ElementRef] : errors on this line, so i had to comment it out
2. cant use @View decorator because @View and @Component have been merged together
3. Using kendo controls on html template breaks.

Are you planning on updating this version, looks a little outdated to me. 

Any help would be really appreciated.

Thank you

**Comment by aikeru** [comment]
Thanks for your bug report! :) Yes, Angular2 has changed a lot in recent months. I plan to update it when I have time.

**Comment by gauravbhanderi231** [comment]
Thanks for the update. I was able to make some modifications to your code
and get it working. But please keep us updated when you modify your code.

**Comment by aikeru** [comment]
@gauravbhanderi231 I have updated the project to support Angular 4, since that is now officially released. Hopefully that will keep things stable for awhile. If you have a new issue with Angular 4, please let me know.
I'm sorry but I don't have time to maintain and test legacy versions for this little repo. :(
Angular moves quickly.
